use super::*;
use crate::platform::windows::apps_folder::PackageIdentity;

fn entry(name: &str, app_id: &str) -> StartAppEntry {
    StartAppEntry {
        name: name.into(),
        app_id: app_id.into(),
        target: None,
        package: None,
    }
}

fn targeted(name: &str, app_id: &str, target: &str) -> StartAppEntry {
    StartAppEntry {
        target: Some(target.into()),
        ..entry(name, app_id)
    }
}

fn packaged(name: &str, app_id: &str) -> StartAppEntry {
    StartAppEntry {
        package: Some(PackageIdentity {
            full_name: "OpenAI.Codex_26.727.4816.0_x64__2p2nqsd0c76g0".into(),
            install_location: Some(
                r"C:\Program Files\WindowsApps\OpenAI.Codex_26.727.4816.0_x64__2p2nqsd0c76g0"
                    .into(),
            ),
        }),
        ..entry(name, app_id)
    }
}

fn no_executables() -> HashMap<String, String> {
    HashMap::new()
}

fn converted(entries: Vec<StartAppEntry>, executables: &HashMap<String, String>) -> Vec<AppInfo> {
    let never_cancelled = || false;
    build_start_apps(&ScanControl::new(&never_cancelled), entries, executables)
}

#[test]
fn ignores_resource_and_replacement_character_names() {
    let apps = converted(
        vec![
            entry("ms-resource:AppName", "Package!App"),
            entry("Broken\u{fffd}Name", "Broken!App"),
        ],
        &no_executables(),
    );

    assert!(apps.is_empty());
}

#[test]
fn maps_an_apps_folder_entry_onto_a_catalog_record() {
    let apps = converted(
        vec![entry("Codex", "OpenAI.Codex_abc!App")],
        &no_executables(),
    );

    assert_eq!(apps[0].name, "Codex");
    assert_eq!(apps[0].path, "OpenAI.Codex_abc!App");
    assert_eq!(apps[0].launch_kind, LaunchKind::AppUserModelId);
}

#[test]
fn preserves_generic_host_targets_as_launch_evidence() {
    let apps = converted(
        vec![
            targeted(
                "Ubuntu",
                "Microsoft.AutoGenerated.{WSL}",
                r"C:\Program Files\WSL\wsl.exe",
            ),
            targeted(
                "Командная строка",
                r"X\cmd.exe",
                r"C:\Windows\system32\cmd.exe",
            ),
            targeted(
                "Reload Configuration",
                "Microsoft.AutoGenerated.{F5}",
                r"C:\Program Files\PostgreSQL\15\bin\pg_ctl.exe",
            ),
        ],
        &no_executables(),
    );

    let ubuntu = apps.iter().find(|app| app.name == "Ubuntu").unwrap();
    assert_eq!(
        ubuntu.resolved_path.as_deref(),
        Some(r"C:\Program Files\WSL\wsl.exe")
    );
    let cmd = apps.iter().find(|a| a.name == "Командная строка").unwrap();
    assert_eq!(
        cmd.resolved_path.as_deref(),
        Some(r"C:\Windows\system32\cmd.exe")
    );
    let reload = apps
        .iter()
        .find(|a| a.name == "Reload Configuration")
        .unwrap();
    assert!(reload.resolved_path.is_some(), "dedicated tool target kept");
}

#[test]
fn resolves_start_app_target_into_resolved_path() {
    let apps = converted(
        vec![targeted(
            "Просмотр событий",
            "Microsoft.AutoGenerated.{BB044BFD}",
            r"C:\Windows\system32\eventvwr.msc",
        )],
        &no_executables(),
    );

    assert_eq!(apps.len(), 1);
    assert_eq!(apps[0].name, "Просмотр событий");
    assert_eq!(
        apps[0].resolved_path.as_deref(),
        Some(r"C:\Windows\system32\eventvwr.msc")
    );
}

#[test]
fn trusted_mysql_installer_target_is_classified_without_parsing_the_aumid() {
    let apps = converted(
        vec![targeted(
            "MySQL Installer - Community",
            "Microsoft.AutoGenerated.{2C7C9013-A7FD-5C12-D811-939AFE2A3592}",
            r"C:\Program Files (x86)\MySQL\MySQL Installer for Windows\MySQLInstaller.exe",
        )],
        &no_executables(),
    );

    assert_eq!(
        apps[0].artifact_kind,
        crate::catalog::ArtifactKind::Installer
    );
    assert_eq!(
        apps[0].category,
        crate::catalog::AppCategory::InstallersDocs
    );
}

#[test]
fn parses_url_backed_start_apps_as_documentation() {
    let apps = converted(
        vec![targeted(
            "Node.js website",
            "https://nodejs.org/",
            "https://nodejs.org/",
        )],
        &no_executables(),
    );

    assert_eq!(apps.len(), 1);
    assert_eq!(
        apps[0].artifact_kind,
        crate::catalog::ArtifactKind::Documentation
    );
    assert_eq!(
        apps[0].category,
        crate::catalog::AppCategory::InstallersDocs
    );
}

#[test]
fn keeps_start_apps_with_product_words_in_names_or_aumids() {
    let apps = converted(
        vec![
            entry(
                "Visual Studio Installer",
                "Microsoft.VisualStudio.Installer",
            ),
            entry("Uninstall Node.js", "Microsoft.AutoGenerated.Uninstall"),
            entry("Visual Studio Code", "Microsoft.VisualStudioCode"),
        ],
        &no_executables(),
    );

    assert_eq!(
        apps.iter().map(|app| app.name.as_str()).collect::<Vec<_>>(),
        vec![
            "Visual Studio Installer",
            "Uninstall Node.js",
            "Visual Studio Code"
        ]
    );
}

#[test]
fn a_packaged_entry_becomes_an_uninstallable_msix_record() {
    let apps = converted(
        vec![packaged("Codex", "OpenAI.Codex_2p2nqsd0c76g0!App")],
        &no_executables(),
    );

    assert_eq!(apps[0].source_kind, SourceKind::Msix);
    assert_eq!(apps[0].publisher.as_deref(), Some("OpenAI"));
    assert_eq!(apps[0].version.as_deref(), Some("26.727.4816.0"));
    assert_eq!(apps[0].product_name.as_deref(), Some("OpenAI.Codex"));
    assert!(apps[0].can_uninstall);
    assert_eq!(apps[0].resolved_path, None);
}

#[test]
fn a_packaged_entry_resolves_its_executable_from_the_package_repository() {
    let executables = HashMap::from([(
        "openai.codex_2p2nqsd0c76g0!app".to_string(),
        r"app\ChatGPT.exe".to_string(),
    )]);

    let apps = converted(
        vec![packaged("Codex", "OpenAI.Codex_2p2nqsd0c76g0!App")],
        &executables,
    );

    assert_eq!(
        apps[0].resolved_path.as_deref(),
        Some(
            r"C:\Program Files\WindowsApps\OpenAI.Codex_26.727.4816.0_x64__2p2nqsd0c76g0\app\ChatGPT.exe"
        )
    );
}

#[test]
fn a_packaged_entry_ignores_an_executable_registered_for_another_application() {
    let executables = HashMap::from([(
        "other.package_abc!app".to_string(),
        r"app\ChatGPT.exe".to_string(),
    )]);

    let apps = converted(
        vec![packaged("Codex", "OpenAI.Codex_2p2nqsd0c76g0!App")],
        &executables,
    );

    assert_eq!(apps[0].resolved_path, None);
}
